accounts/urls.py
from django.urls import path,re_path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name = 'register'),
    path('logout/', logout_view , name = 'logout'),
]

blog/urls.py
from django import urls
from  home.views import  home_view
from  about.views import about_view
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('about/', about_view),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path,re_path
from .views import *

app_name='post'

urlpatterns = [
    path('index/',index_view,name='index'),
    path('create/',create_view,name='create'),
    re_path(r'^(?P<id>\d+)/delete/$',delete_view,name='delete'),
    re_path(r'^(?P<id>\d+)/update/$',update_view,name='update'),
    re_path(r'^(?P<id>\d+)/$',detail_view,name='detail')
]

about/models.py
from django.db import models

# Create your models here.

accounts/models.py
from django.db import models
from django.contrib.auth import models

home/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.
class Post(models.Model):
    author = models.ForeignKey("auth.user", verbose_name = "نویسنده", on_delete=models.PROTECT)
    title=models.CharField(max_length=120,verbose_name='عنوان')
    content=RichTextField(verbose_name='متن')
    published_date=models.DateTimeField(verbose_name='تاریخ انتشار',auto_now_add=True)
    image = models.ImageField(null=True,blank=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post:detail',kwargs={'id':self.id})

    def get_update_url(self):
        return reverse('post:update',kwargs={'id':self.id})
    
    def get_delete_url(self):
        return reverse('post:delete',kwargs={'id':self.id})

    class Meta:
        ordering=['-published_date']


class Comment(models.Model):
    post=models.ForeignKey("post.Post",related_name="comments", on_delete=models.CASCADE)
    name=models.CharField(max_length=120, verbose_name="نام")
    content=models.TextField(verbose_name="دیدگاه")
    created_date=models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.forms import fields

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('wrong Username or Password')
        return super(LoginForm, self).clean()

class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100)
    password1 = forms.CharField(max_length=100, label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=100, label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
        ]

    def clean_password(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Password Not Matching ...')

        return password2

post/forms.py
from django import forms
from django.forms import fields 
from .models import Post,Comment
from captcha.fields import ReCaptchaField

class PostForm(forms.ModelForm):

    captcha=ReCaptchaField()

    class Meta:
        model=Post
        fields=[
            'title',
            'content',
            'image',
        ]

class CommentForm(forms.ModelForm):

    captcha=ReCaptchaField()

    class Meta:
        model=Comment
        fields=[
            'name',
            'content'
        ]

about/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.
def about_view(request):
    context={'Name':'Shahin'}
    return render(request,'about.html',context)

accounts/views.py
from django.shortcuts import render,redirect
from .forms import LoginForm,RegisterForm
from django.contrib.auth import authenticate,login,logout

def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    return render(request, 'accounts/form.html', {'form':form , 'title':'Login'})

def register_view(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password1')
        user.set_password(password)
        user.is_staff = user.is_superuser = True
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        return redirect('home')
    return render(request, 'accounts/form.html', {'form':form, 'title':'Register'})

def logout_view(request):
    logout(request)
    return redirect('home')

home/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.
def home_view(request):
    return render(request,'home.html',{'Name':'Saleh'})

post/views.py
from django.shortcuts import redirect, render,HttpResponse,get_object_or_404,HttpResponseRedirect,redirect,Http404
from .models import Post
from .forms import PostForm , CommentForm
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
# Create your views here.


def index_view(request):
    posts=Post.objects.all()

    query=request.GET.get('q')
    if query:
        posts=posts.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(author__first_name__icontains=query) |
            Q(author__last_name__icontains=query) 

        ).distinct()
    
    paginator = Paginator(posts,5)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    
    return render(request,'post/index.html',{'posts':posts})

def create_view(request):

    if not request.user.is_authenticated:
        return Http404()
   
    form=PostForm(request.POST or None , request.FILES or None)
    if form.is_valid():
       post=form.save(commit=False)
       post.author=request.user
       post=form.save()
       messages.success(request,"POst created successfully",extra_tags='msg')
       return HttpResponseRedirect(post.get_absolute_url())
    context={
        'form':form
    }
    return render(request,'post/form.html',context)

def detail_view(request,id):
    post=get_object_or_404(Post,id=id)
    form=CommentForm(request.POST or None)
    if form.is_valid():
        comment=form.save(commit=False)
        comment.post=post
        comment=form.save()

    context={
        "post":post,
        "form":form
    }
    return render(request,'post/detail.html',context)
 
def update_view(request,id):

    if not request.user.is_authenticated:
        return Http404()

    if not request.user.is_authenticated:
        return Http404()

    post=get_object_or_404(Post,id=id)

    form=PostForm(request.POST or None, request.FILES or None , instance=post)
    if form.is_valid():
        form.save()
        messages.success(request,"POst created successfully",extra_tags='msg')

        return HttpResponseRedirect(post.get_absolute_url()) 
    context={
        'form':form
    }
    return render(request,'post/form.html',context)

def delete_view(request,id):
    post=get_object_or_404(Post,id=id)
    post.delete()
    return redirect('post:index')

templates/about.html
{% extends 'base.html' %} {% block title %} About Page {{block.super}} {% endblock %} {% block body %}

<h1 align='center'>Hey {{Name}} Welcome to About_page ........</h1>

{% endblock %}

templates/accounts/form.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block body %}
<h1> {{ title }}</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{ form|crispy }}
    <button class="btn btn-primary" type="submit"> {{ title }}</button>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html en="en">

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>{% block title %} Tutorial Django {% endblock %}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <script src='main.js'></script>
</head>

<body>
    <div class="container">
        {% include 'header.html' %} {% include 'message.html ' %}
        <!--<img src="{% static 'image.jpg' %}" width='50%' height="50%">-->
        {% block body %} {% endblock %}
    </div>


    <script src={% static '/js/jquery.min.js' %}></script>
    <script src={% static '/js/bootstrap.min.js' %}></script>
</body>

</html>

templates/header.html
<!-- Navigation Menu -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top ">

    <div class="container">
        <!-- Container -->

        <a class="navbar-brand" href="#"><strong>CodeFriend.ir</strong></a>
        <!-- Navbar Brand -->

        <!-- Navbar Toggler Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Nav Links -->
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post:index' %}">Blog</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post:create' %}">Write</a>
                </li>
                {% endif %} {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                {% endif %}
            </ul>

            <!-- Search Box -->
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" name='q' value="{{request.GET.q}}" type="search" placeholder="Search in blog">
                <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
            </form>

        </div>

    </div>

</nav>

templates/home.html
{% extends 'base.html' %}{% block title %} Home Page {{block.super}} {% endblock %} {% block body %}
<h1 class="text-center">Hey {% if request.user.get_full_name %}{{ request.user.get_full_name }} {% elif request.user.get_username %} {{ request.user.get_username}}{% else %}
    <h3 class="text-center font-italic"> New User</h3>{% endif %},
    <h3 class="text-center"> Welcome to Home page ........</h3>
</h1>
{% endblock %}

templates/message.html
{% if messages %} {% for message in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
</div>
{% endfor %} {% endif %}

templates/post/comment.html
{% load crispy_forms_tags %}
<form method="post">
    {% csrf_token %} {{form|crispy}}
    <button class="btn btn-primary"> ارسال دیدگاه</button>
</form>

templates/post/detail.html
{% extends 'base.html' %} {% block title %} Detail Page - {{block.super}} {% endblock %} {% block body %}

<div class="row">
    <div class="card col-md-8 offset-md-2">
        <div class="card-body">
            {% if post.image %}
            <img src="{{ post.image.url }}" class="img-fluid"> {% endif %}
            <h5 class="card-title">{{post.title}} <small> {{post.published_date|timesince}} before</small></h5>
            <h6>نویسنده : {{ post.author.get_full_name }}</h6>
            <p class="card-text">{{post.content|safe|linebreaks}}</p>
            {% if request.user.is_authenticated %}
            <a href="{{post.get_update_url}}" class="btn btn-warning"> Edit</a>
            <a href="{{post.get_delete_url}}" class="btn btn-danger"> Delete</a> {% endif %}
        </div>
    </div>

    <div class="col-md-8 offset-md-2 mt-5">
        <h3 align="right"> دیدگاه ها </h3>
        {% include 'post/comment.html' %} {% for comment in post.comments.all %}
        <br><br>
        <h4>{{comment.name}} | <small>{{comment.created_date|timesince}} ago</small></h4>
        <p>{{comment.content|linebreaks}}</p>
        <br>
        <hr> {% endfor %}
    </div>
</div>

{% endblock %}

templates/post/form.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title %} Form -{{block.super}} {% endblock %} {%block body %}
<h1>Form</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form|crispy }}
    <!-- {{form.as_p}} -->

    {{ form.media }}

    <button type="submit"> انتشار</button>
</form>

{% endblock %}

templates/post/index.html
{%extends 'base.html' %} {% block title %} Detail Page- {{block.super}}{% endblock %} {% block body %} {% for post in posts %}
<div class="row">
    <div class="card col-md-8 offset-md-2">
        <div class="card-body">
            {% if post.image %}
            <img src="{{post.image.url}}" class="img-fluid"> {% endif %}
            <h5 class="card-title">{{post.title}} <small> {{post.published_date|timesince}} before</small></h5>
            <h6> نویسنده: {{ post.author.get_full_name }} </h6>
            <p class="card-text">{{post.content|safe|truncatechars:120}}</p>
            <a href="{{post.get_absolute_url}}" class="btn btn-primary"> view post</a> {% if request.user.is_authenticated %}
            <a href="{{post.get_update_url}}" class="btn btn-warning"> Edit</a>
            <a href="{{post.get_delete_url}}" class="btn btn-danger"> Delete</a> {% endif %}
        </div>
    </div>
</div>
{%endfor%}
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}{% if request.GET.q %} & q={{request.GET.q}} {% endif %}"> previous </a>
        {% endif %}
    <span class="current">
        page {{ posts.number }} of {{ posts.paginator.num_pages }}
    </span> {% if posts.has_next %}
    <a href="?page= {{ posts.next_page_number}}{% if request.GET.q %} & q={{request.GET.q}} {% endif %}"> next </a>
    <a href="?page= {{ posta.paginator.num_pages }}{% if request.GET.q %} & q={{request.GET.q}} {% endif %}"> last &raquo; </a> {% endif %}
    </span>
</div>
< {% endblock %}